name: Kicad

on:
  push:
    paths:
    - '**.sch'
    - '**.lib'
    - '**.kicad_mod'
    - '**.kicad_pcb'
  pull_request:
    paths:
      - '**.sch'
      - '**.lib'
      - '**.kicad_mod'
      - '**.kicad_pcb'

jobs:
  Kicad:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Set version number
      env:
        GITHUB_SHA: ${{ github.sha }}
      run: |
         sed -i "s~\[Uncontrolled\]~${GITHUB_SHA:0:6}~g" Kicad/*.sch Kicad/*.kicad_pcb
    - name: Run KiBot
      uses: nerdyscout/kicad-exports@v2.3
      with:
        config: 'Kicad/docs.kibot.yaml'
        dir: docs
        schema: 'Kicad/neotron-pico.sch'
        board: 'Kicad/neotron-pico.kicad_pcb'
    - name: Upload Results
      uses: actions/upload-artifact@v2
      with:
        name: docs
        path: docs
