on:
  push:
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Upload Release

jobs:
  build:
    name: Upload Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Get Branch Name
        id: branch_name
        run: |
          echo ::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}
          echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
      - name: Set version number
        env:
          SOURCE_TAG: ${{ steps.branch_name.outputs.SOURCE_TAG }}
        run: |
          sed -i "s~\[Uncontrolled\]~${SOURCE_TAG}~g" Kicad/*.sch Kicad/*.kicad_pcb
      - name: Build project
        uses: nerdyscout/kicad-exports@v2.3
        with:
          config: 'Kicad/docs.kibot.yaml'
          dir: docs
          schema: 'Kicad/neotron-pico.sch'
          board: 'Kicad/neotron-pico.kicad_pcb'
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ steps.branch_name.outputs.SOURCE_TAG }}
          draft: false
          prerelease: false
      - name: Build gerbers zip file
        run: |
          zip -r --junk-paths neotron-pico-gerbers.zip docs/gerbers/
      - name: Upload files to Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            neotron-pico-gerbers.zip
            docs/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
